# Generated by Django 6.0.2 on 2026-02-15 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('badge_text', models.CharField(default='Model', max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hero_image', models.URLField(blank=True, max_length=500, null=True)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('horsepower', models.CharField(blank=True, max_length=100)),
                ('fuel_economy', models.CharField(blank=True, max_length=100)),
                ('top_speed', models.CharField(blank=True, max_length=100)),
                ('acceleration', models.CharField(blank=True, max_length=100)),
                ('drivetrain', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('comfort_features', models.JSONField(blank=True, default=list)),
                ('safety_features', models.JSONField(blank=True, default=list)),
                ('technology_features', models.JSONField(blank=True, default=list)),
                ('performance_features', models.JSONField(blank=True, default=list)),
                ('gallery_exterior', models.JSONField(blank=True, default=list)),
                ('gallery_interior', models.JSONField(blank=True, default=list)),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('displacement', models.CharField(blank=True, max_length=50)),
                ('max_power', models.CharField(blank=True, max_length=100)),
                ('max_torque', models.CharField(blank=True, max_length=100)),
                ('compression_ratio', models.CharField(blank=True, max_length=50)),
                ('fuel_system', models.CharField(blank=True, max_length=100)),
                ('transmission_type', models.CharField(blank=True, max_length=100)),
                ('drivetrain_type', models.CharField(blank=True, max_length=100)),
                ('front_suspension', models.CharField(blank=True, max_length=100)),
                ('rear_suspension', models.CharField(blank=True, max_length=100)),
                ('steering', models.CharField(blank=True, max_length=100)),
                ('brakes_front', models.CharField(blank=True, max_length=100)),
                ('brakes_rear', models.CharField(blank=True, max_length=100)),
                ('wheels_front', models.CharField(blank=True, max_length=100)),
                ('wheels_rear', models.CharField(blank=True, max_length=100)),
                ('curb_weight', models.CharField(blank=True, max_length=50)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('width', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('wheelbase', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'brand', 'model'],
                'indexes': [models.Index(fields=['brand', 'model'], name='showroom_ca_brand_a2cb60_idx'), models.Index(fields=['year'], name='showroom_ca_year_658496_idx')],
            },
        ),
    ]
