# Generated by Django 6.0.2 on 2026-02-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='display_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
