# Generated by Django 6.0.2 on 2026-02-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_car_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
    ]
