# Generated by Django 6.0.2 on 2026-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_remove_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='similar_cars',
            field=models.ManyToManyField(blank=True, to='showroom.car'),
        ),
    ]
