# Generated by Django 6.0.1 on 2026-02-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0007_car_similar_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='similar_cars',
            field=models.ManyToManyField(blank=True, related_name='similar_to', to='showroom.car'),
        ),
    ]
