# Generated by Django 6.0.1 on 2026-02-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0008_alter_car_similar_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='similar_cars',
            field=models.ManyToManyField(blank=True, to='showroom.car'),
        ),
    ]
